### ISSUE TITLE
Proposed SIG-Core meeting agenda - 15/OCT/2021 0900PT/1600GMT

### ISSUE THREAD

**Issue by amzn-pratikpa** [o3de/sig-core#13]
## Meeting Details

- **Date/Time:** : 15/OCT/2021, 0900 PT/1600 GMT
- **Location:** [Discord SIG-Core Voice Room](https://discord.gg/WtmTC6erDP)
- **Moderator:** @amzn-pratikpa 
- **Note Taker** Volunteers welcome!

The [SIG-Core Meetings](https://github.com/o3de/sig-core/tree/main/meetings) repo contains the history past calls, including a link to the agenda, recording, notes, and resources.

## Meeting Agenda
- Split SIG-Core into more SIG's (@ppinfel)
- Add the Guideline Support Library to AzCore (@hultonha)
- Nomination of @burelc-amzn to be a maintainer (@amzn-pratikpa)
- Removal of PhysXSamples gem. (@moraaar)

**Please comment on this for anything you would like added to the agenda**

**Comment by ppinfel** [comment]
are we gonna split up sig-core into more sigs

**Comment by amzn-pratikpa** [comment]
> I would be interested to know if there's interest in adding the Guideline Support Library (GSL) https://github.com/microsoft/GSL to AzCore (potentially AzFramework).
> 
> The GSL has some incredibly useful types (e.g. `gsl::span`, coming in `std::` in C++20). Adopting it would help us conform to the C++ Core Guidelines that build on top of this library (https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines). There's some useful techniques gaining wider use such as using `zstring` to explicitly refer to a null terminated string (as opposed to `const char*` that could refer to a single character or `char` array).
> 
> The library is designed to encourage safe and secure use of C++ adopting the zero-overhead mindset we've come to expect from C++ libraries.
> 
> This would likely need to be an RFC before it can be adopted but I'd be interested to take the temperature of the room to see if there's interest or not before spending more time on it.

Added to the agenda

**Comment by amzn-pratikpa** [comment]
> I'd like to discuss the removal of PhysXSamples gem.

Added to the agenda
