### ISSUE TITLE
Proposed SIG-Core meeting agenda Date/Time: 2/DEC/2021 0900 PST/1700 GMT

### ISSUE THREAD

**Issue by amzn-pratikpa** [o3de/sig-core#20]
## Meeting Details

- **Date/Time:** 2/DEC/2021 0900 PST/1700 GMT
- **Location:** [Discord SIG-Core Voice Room](https://discord.gg/WtmTC6erDP)
- **Moderator:** @amzn-pratikpa 
- **Note Taker** Please volunteer if you're willing to take notes

The [SIG-Core Meetings](https://github.com/o3de/sig-core/tree/main/meetings) repo contains the history past calls, including a link to the agenda, recording, notes, and resources.

## SIG Updates

**What happened since the last meeting?**
- @burelc-amzn is now a maintainer

## Meeting Agenda

- IMGUI currently doesn't have an owner. While @o3de/sig-graphics-audio own the rendering side, they don't intend to own the integration or updates. Can @o3de/sig-core take ownership of it?
- Localisation: @sptramer would like to discuss the underlying issue behind https://github.com/o3de/o3de/issues/5983
- Nomination of user @nemerle to become a reviewer.

**Please comment on additional agenda items in the comments**

**Comment by amzn-pratikpa** [comment]
> Would like to discuss the following issue ([o3de/o3de#5983](https://github.com/o3de/o3de/issues/5983)) on the agenda:
> 
> There are a number of localization issues that seem to have come in lately regarding the display of non-ASCII characters, especially Chinese. It's unclear if this is an issue with the Qt bindings directly, or because internal string representations may not support extended characters. Regardless:
> 
> The localization pipeline in O3DE is actually a problem right now: The support is, as far as I know, still from legacy Cry. I don't think it's useful to start designing a loc-loading system (or if an improvement even needs to be made yet) but I _would_ like to get an audit of some base internal AzCore structures (like String) for these purposes - plus also the purpose of eventual API documentation.

Added to agenda

**Comment by bosnichd** [comment]
SIG Reviewer nomination for @nemerle: https://github.com/o3de/sig-core/issues/21
