### ISSUE TITLE
SIG Reviewer/Maintainer Nomination

### ISSUE THREAD

**Issue by bosnichd** [o3de/sig-core#21]
### Nomination Guidelines
**Reviewer Nomination Requirements**
* 6+ contributions successfully submitted to O3DE
* 100+ lines of code changed across all contributions submitted to O3DE
* 2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

**Maintainer Nomination Requirements**
* Has been a Reviewer for 2+ months
* 8+ reviewed Pull Requests in the previous 2 months
* 200+ lines of code changed across all reviewed Pull Request
* 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate @nemerle, to become a Reviewer on behalf of sig-core. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile: https://github.com/nemerle

https://github.com/o3de/o3de/commits?author=nemerle

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by lumberyard-employee-dm** [comment]
I support the nomination of @nemerle for a role of Reviewer for sig-core.

**Comment by amznestebanpapp** [comment]
I support the nomination of @nemerle for a role of Reviewer for sig-core.

**Comment by amzn-pratikpa** [comment]
@nemerle was unanimously approved as a reviewer in the SIG-Core meeting held on 2/DEC/2021

**Comment by amzn-changml** [comment]
@nemerle has been invited to the sig-core-reviewers group, which is a subgroup of Reviewers
