### ISSUE TITLE
Add a C++ Best Practice page to governance 

### ISSUE THREAD

**Issue by lumberyard-employee-dm** [o3de/sig-core#32]
@santorac  Has reached out looking to add the [C++ Best Practice Page]() to the public github o3de/sig-core repo for governance.
The C++ Best Practices Page is a set of guidelines that developers can use(but is not required to use) to lookup previous solutions to problems found when using O3DE. The guidance is meant to help developers avoid pitfalls with some O3DE specific constructs.

There is a Lumberyard Best Practices page, that can perhaps be used as a base for creating a full Best Practice page.

A sanitized version of that page has been attached to this issue.
[C++-Best-Practices-Guide.md](https://github.com/o3de/sig-core/files/8356201/C%2B%2B-Best-Practices-Guide.md)

**Comment by hultonha** [comment]
Thanks for starting this @lumberyard-employee-dm! I did another pass on the .md file to clean-up the conversion from Jira. It now should be in a good place to add to the repo if we agree on the content (tagging @santorac for visibility).

[C++-Best-Practices-Guide.md](https://github.com/o3de/sig-core/files/8380471/C%2B%2B-Best-Practices-Guide.md)

**Comment by lumberyard-employee-dm** [comment]
It looks fine to me.

**Comment by hultonha** [comment]
> It looks good to me.

Good to hear! Let me know if it's worth creating a PR for this soon

**Comment by hultonha** [comment]
PR now created here - https://github.com/o3de/sig-core/pull/36

**Comment by hultonha** [comment]
Resolved by https://github.com/o3de/sig-core/pull/36
