### ISSUE TITLE
SIG Reviewer/Maintainer Nomination: @amzn-phist

### ISSUE THREAD

**Issue by lumberyard-employee-dm** [o3de/sig-core#34]
### Nomination Guidelines
**Reviewer Nomination Requirements**
* 6+ contributions successfully submitted to O3DE
* 100+ lines of code changed across all contributions submitted to O3DE
* 2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

**Maintainer Nomination Requirements**
* Has been a Reviewer for 2+ months
* 8+ reviewed Pull Requests in the previous 2 months
* 200+ lines of code changed across all reviewed Pull Request
* 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate: ***@amzn-phist***, to become a ***Maintainer*** on behalf of ***sig-core***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***https://github.com/amzn-phist***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by lumberyard-employee-dm** [comment]
@o3de/sig-core has no objections.

**Comment by amzn-pratikpa** [comment]
Invited @amzn-phist to be a maintainer. I will close this issue as soon as he accepts

**Comment by amzn-phist** [comment]
I accept.
