### ISSUE TITLE
Proposed SIG-Core meeting agenda for 3/AUG/2022

### ISSUE THREAD

**Issue by amzn-pratikpa** [o3de/sig-core#42]
## Meeting Details

- **Date/Time:** 3/AUG/2022 @ 09:00am PT / 12:00pm ET.

- **Location:** [Discord SIG-Core Voice Room](https://discord.gg/WtmTC6erDP)
- **Moderator:** @amzn-pratikpa 
- **Note Taker** Volunteers needed!

The [SIG-Core Meetings](https://github.com/o3de/sig-core/tree/main/meetings) repo contains the history past calls, including a link to the agenda, recording, notes, and resources.

## Meeting Agenda

* C++20: Why, when and how we should upgrade the code base to C++20
* How can we reduce the sensitivity of the error messages displayed in the console. @yuyihsu 
Please post additional agenda items in the comments so they can be added to the meeting agenda

**Comment by yuyihsu** [comment]
How can we reduce the sensitivity of the error messages displayed in the console.

**Comment by yuyihsu** [comment]
Hi @amzn-pratikpa , has this meeting happened already? If not, when is it scheduled?

**Comment by lumberyard-employee-dm** [comment]
Closing as the meeting has already occured
