### ISSUE TITLE
SIG-Core meeting agenda for 14-SEPT-2022

### ISSUE THREAD

**Issue by amzn-pratikpa** [o3de/sig-core#45]
## Meeting Details

- **Date/Time:** 14-SEPT-2022 @ 0900 PT / 1700 BST
- **Location:** [Discord SIG-Core Voice Room](https://discord.gg/WtmTC6erDP)
- **Moderator:** @amzn-pratikpa 
- **Note Taker** TBD

The [SIG-Core Meetings](https://github.com/o3de/sig-core/tree/main/meetings) repo contains the history past calls, including a link to the agenda, recording, notes, and resources.

## SIG Updates

**What happened since the last meeting?**

## Meeting Agenda

* Elections for SIG chair and co-chair: Decide on a timeline and process to nominate and vote on the next two people to run the SIG for 12 months

Please comment below on any additional items you'd like to add to the agenda.

Discuss @AMZN-alexpete RFC for engine versioning https://github.com/o3de/sig-core/issues/44

Discuss SIG-Core stance on Console Support and how it affects the C++ standard that O3DE uses

**Discuss agenda from proposed topics**

## Outcomes from Discussion topics

**Discuss outcomes from agenda**

## Action Items

**Create actionable items from proposed topics**

## Open Discussion Items

List any additional items below!

**Comment by lumberyard-employee-dm** [comment]
Closing issue as the meeting has occurred.
