### ISSUE TITLE
Create Roadmap View

### ISSUE THREAD

**Issue by vincent6767** [o3de/sig-core#49]
Hi! SIG release is working to help the O3DE community to get visibility of the O3DE roadmap. Full context can be read here: https://github.com/o3de/sig-release/issues/79. 

In order to achieve that goal, we need your help to create the roadmap for your SIG by **February 6th, 2023**, and start giving brief updates about the roadmap items at the **Joint TSC meeting on February 28th, 2023**. Instruction to create the roadmap view can be read in the RFC section "Roadmap Review in TSC monthly meeting".

Let me know if you have any concerns with the dates or any questions about the ask!

**Comment by vincent6767** [comment]
Awesome. Thanks, @lumberyard-employee-dm ! One question. I don't see any of the items marked as kind/roadmap. Is that intended? As a reminder, a roadmap item communicates the initiative and vision of the SIG.

**Comment by lumberyard-employee-dm** [comment]
> Awesome. Thanks, @lumberyard-employee-dm ! One question. I don't see any of the items marked as kind/roadmap. Is that intended? As a reminder, a roadmap item communicates the initiative and vision of the SIG.

I have updated the kind/roadmap for items that SIG-Core plan for the future

**Comment by vincent6767** [comment]
Thanks @lumberyard-employee-dm BTW, I see you created the project in the O3DE repo instead of in the SIG Repo. Based on the RFC, the projects live in the SIG repo. Is it possible to move the project into the SIG repo? If it's not too much effort, then please link the SIG Core roadmap project in the O3DE repo to this SIG repo
![image](https://user-images.githubusercontent.com/15702735/216522387-cd34fcb4-d0d9-4431-a12c-5422be958d04.png)

**Comment by lumberyard-employee-dm** [comment]
The reason the project lives in the O3DE organization instead of the SIG-Core, repo is to allow it to add issues from ALL the O3DE repos.
If the project is part of the SIG-Core repo, it can only add issues from the repo to it.

**Comment by vincent6767** [comment]
Okay. Understood. Let's not worry about that now. Can you help link the roadmap to this SIG repo? There is a link project option if you go to the Projects tab. @lumberyard-employee-dm

**Comment by vincent6767** [comment]
@lumberyard-employee-dm Nevermind. I link the roadmap project to the SIG Repo. Should not affect anything.
