### ISSUE TITLE
Proposed SIG-Core meeting agenda  (Date:21/JUL/2021/Time: 0900 PST, 1700 BST)

### ISSUE THREAD

**Issue by amzn-pratikpa** [o3de/sig-core#8]
## Meeting Details

- **Date/Time:** Date:21/JUL/2021/Time: 0900 PST, 1700 BST
- **Location:** [Discord SIG-Core Voice Room](https://discord.gg/WtmTC6erDP)
- **Moderator:** Pratik Patel (@amzn-pratikpa)
- **Note Taker** TBD

The [SIG-Core Meetings](https://github.com/o3de/sig-core/tree/main/meetings) repo contains the history past calls, including a link to the agenda, recording, notes, and resources.

## SIG Updates

**What happened since the last meeting?**
* Discussed SIG Charter and agreed it was too broad. 
* Consensus was that a mission statement would help narrow the focus of the charter

## Meeting Agenda
* Discuss any proposed mission statements: https://github.com/o3de/sig-core/issues/9
* Discuss coding standards: https://github.com/o3de/sig-core/pull/5
* Continue discussion about SIG charter 

Please list any additional items you would like to add to the agenda in the comments.

**Comment by hultonha** [comment]
I would be interested to know if there's interest in adding the Guideline Support Library (GSL) https://github.com/microsoft/GSL to AzCore (potentially AzFramework).

The GSL has some incredibly useful types (e.g. `gsl::span`, coming in `std::` in C++20). Adopting it would help us conform to the C++ Core Guidelines that build on top of this library (https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines). There's some useful techniques gaining wider use such as using `zstring` to explicitly refer to a null terminated string (as opposed to `const char*` that could refer to a single character or `char` array).

The library is designed to encourage safe and secure use of C++ adopting the zero-overhead mindset we've come to expect from C++ libraries.

This would likely need to be an RFC before it can be adopted butI would be interested to know if there's interest in adding the Guideline Support Library (GSL) https://github.com/microsoft/GSL to AzCore (potentially AzFramework).

The GSL has some incredibly useful types (e.g. `gsl::span`, coming in `std::` in C++20). Adopting it would help us conform to the C++ Core Guidelines that build on top of this library (https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines). There's some useful techniques gaining wider use such as using `zstring` to explicitly refer to a null terminated string (as opposed to `const char*` that could refer to a single character or `char` array).

The library is designed to encourage safe and secure use of C++ adopting the zero-overhead mindset we've come to expect from C++ libraries.

This would likely need to be an RFC before it can be adopted but I'd be interested to take the temperature of the room to see if there's interest or not before spending more time on it. I'd be interested to take the temperature of the room to see if there's interest or not before spending more time on it.

**Comment by amzn-pratikpa** [comment]
> I would be interested to know if there's interest in adding the Guideline Support Library (GSL) https://github.com/microsoft/GSL to AzCore (potentially AzFramework).
> 
> The GSL has some incredibly useful types (e.g. `gsl::span`, coming in `std::` in C++20). Adopting it would help us conform to the C++ Core Guidelines that build on top of this library (https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines). There's some useful techniques gaining wider use such as using `zstring` to explicitly refer to a null terminated string (as opposed to `const char*` that could refer to a single character or `char` array).
> 
> The library is designed to encourage safe and secure use of C++ adopting the zero-overhead mindset we've come to expect from C++ libraries.
> 
> This would likely need to be an RFC before it can be adopted but I'd be interested to take the temperature of the room to see if there's interest or not before spending more time on it.

@hultonha Did you mean to comment on the other meeting proposal? https://github.com/o3de/sig-core/issues/13
